#! /bin/bash

CUR_DIR=$(pwd)

TERMINATOR_CONFIG_DIR=$HOME"/.config/terminator/"
TERMINATOR_CONFIG_FILE=$TERMINATOR_CONFIG_DIR"/config"

test -f "$TERMINATOR_CONFIG_FILE" && test ! -L "$TERMINATOR_CONFIG_FILE" && mv -v "$TERMINATOR_CONFIG_FILE" "$TERMINATOR_CONFIG_FILE".old
ln -sfv "${CUR_DIR}/config" "$TERMINATOR_CONFIG_DIR"
